<a href="https://colab.research.google.com/github/ShraddhaYewale/Machine-Learning/blob/main/OneHotEncoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

One Hot encoding: Converting categorical data into numerical data

In [1]:
import pandas as pd

In [2]:
dt=pd.read_csv("loan.csv")
dt.head(3)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y

In [3]:
dt.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [6]:
dt["Gender"].fillna(dt["Gender"].mode()[0],inplace=True)
dt["Married"].fillna(dt["Married"].mode()[0],inplace=True)

In [7]:
en_data=dt[["Gender","Married"]]

In [9]:
pd.get_dummies(en_data).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Gender_Female  614 non-null    bool
 1   Gender_Male    614 non-null    bool
 2   Married_No     614 non-null    bool
 3   Married_Yes    614 non-null    bool
dtypes: bool(4)
memory usage: 2.5 KB

In [10]:
from sklearn.preprocessing import OneHotEncoder

In [15]:
ohe=OneHotEncoder(drop="first")
ohe.fit_transform(en_data).toarray()

array([[1., 0.],
       [1., 1.],
       [1., 1.],
       ...,
       [1., 1.],
       [1., 1.],
       [0., 0.]])

In [16]:
pd.DataFrame(ohe.fit_transform(en_data).toarray(),columns=["Gender_Male","Married_Yes"])

     Gender_Male  Married_Yes
0            1.0          0.0
1            1.0          1.0
2            1.0          1.0
3            1.0          1.0
4            1.0          0.0
..           ...          ...
609          0.0          0.0
610          1.0          1.0
611          1.0          1.0
612          1.0          1.0
613          0.0          0.0

[614 rows x 2 columns]